"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

export type PageKey = "home" | "about" | "products" | "quality" | "packaging" | "contact";
type Lang = "en" | "es";
type Copy = Record<string, string>;

const copy: Record<Lang, Copy> = {
  en: {
    home: "Home", about: "About Us", products: "Products", quality: "Quality", packaging: "Packaging", contact: "Contact",
    eyebrow: "Grown high. Supplied globally.", heroTitle: "Bolivian superfoods, ready for your market.", heroText: "Premium Royal Quinoa and Chia Seeds for importers, distributors and food manufacturers — sourced with care from the Bolivian Altiplano.", quote: "Request a quote", explore: "Explore products",
    trust1: "Origin-led sourcing", trust2: "Export-ready supply", trust3: "Flexible bulk formats", trust4: "Buyer-first service",
    introEyebrow: "From altitude to opportunity", introTitle: "A dependable route to authentic Bolivian ingredients.", introText: "We connect international buyers with carefully selected quinoa and chia through clear specifications, responsive communication and practical export support.", learn: "Discover our approach",
    productsEyebrow: "Our portfolio", productsTitle: "Two powerful ingredients. Multiple possibilities.", quinoa: "Bolivian Royal Quinoa", quinoaText: "Large, naturally distinctive grains from Bolivia’s high-altitude growing regions, available in white, red and black varieties.", chia: "Chia Seeds", chiaText: "Clean, uniform seeds for bakery, beverages, cereals, snacks and health-focused formulations.", view: "View product details",
    buyerTitle: "Built around the way B2B buyers work.", buyerText: "From samples and specifications to packaging and shipping documents, we make every step easier to evaluate and move forward.", buyer1: "Clear product specifications", buyer2: "Commercial samples on request", buyer3: "Private-label and bulk options", buyer4: "Export documentation support",
    ctaTitle: "Let’s build your next supply program.", ctaText: "Tell us your required product, volume, destination and packaging. Our team will reply with the right commercial options.",
    aboutEyebrow: "About Altiplano Harvest", aboutTitle: "Rooted in Bolivia. Focused on global buyers.", aboutLead: "We are a specialist B2B supplier connecting the extraordinary growing conditions of the Bolivian Altiplano with ambitious food businesses around the world.", storyTitle: "A focused sourcing partner", storyText: "Our work begins with product fit: the right origin, variety, specification and pack format for each customer. We collaborate with experienced partners close to origin and coordinate the commercial details international buyers need — from samples to shipment.", valuesTitle: "How we work", value1: "Clarity", value1t: "Straight answers, useful documents and realistic lead times.", value2: "Consistency", value2t: "Defined specifications and repeatable supply programs.", value3: "Partnership", value3t: "Practical support built for long-term buyer relationships.",
    productPageTitle: "Ingredients with a story — and a specification.", productPageLead: "Select the origin, variety and format that works for your product line. Final specifications are confirmed with each quotation.", white: "White Royal Quinoa", whiteT: "Mild flavor and light color for retail packs, bowls, bakery and prepared foods.", red: "Red Royal Quinoa", redT: "A firm texture and rich color for blends, salads and premium applications.", black: "Black Royal Quinoa", blackT: "Distinctive dark grains suited to colorful mixes and specialty ranges.", chiaT: "Neutral-tasting whole seeds suited to functional foods, bakery and beverage applications.", details: "Typical options", optQ: "Conventional or organic • cleaned • whole grain • bulk", optC: "Conventional or organic • cleaned • whole seed • bulk", askSpec: "Ask for specification",
    qualityPageTitle: "Quality you can evaluate before you buy.", qualityPageLead: "A transparent, specification-led process supports confident sourcing and consistent receiving.", flow1: "01 · Supplier selection", flow1t: "Origin partners are reviewed for capability, consistency and export readiness.", flow2: "02 · Lot control", flow2t: "Each commercial lot is identified and handled against the agreed product specification.", flow3: "03 · Testing", flow3t: "Relevant quality and safety parameters can be confirmed by lot and buyer requirement.", flow4: "04 · Documentation", flow4t: "Commercial and product documents are coordinated for the destination market.", docTitle: "Documentation by request", docs: "Specification sheet • Certificate of Analysis • Organic documentation where applicable • Packing list • Commercial invoice • Origin and shipping documents",
    packPageTitle: "Packaging built for products, pallets and brands.", packPageLead: "Choose practical export formats for industrial use, distribution or retail-ready programs.", bulk: "Bulk supply", bulkT: "Common formats include lined multiwall paper bags or woven polypropylene bags. Typical net weights: 20 kg, 25 kg or as agreed.", private: "Private label", privateT: "Retail pouch and bag programs can be developed subject to volume, artwork, regulatory and production requirements.", logistics: "Pallet & logistics", logisticsT: "Pallet pattern, container loading and label marks are confirmed before shipment for smooth receiving.", customTitle: "Need a custom format?", customText: "Share your target weight, material, annual volume, label language and destination. We’ll assess the most practical route.",
    contactPageTitle: "Start a clear, useful conversation.", contactPageLead: "Send your sourcing brief and we’ll respond with availability, specifications and next steps.", formTitle: "Request a quotation", name: "Name", company: "Company", email: "Business email", country: "Country / market", interest: "Product interest", volume: "Estimated volume", message: "Requirements", send: "Send inquiry", sent: "Thank you — your inquiry is ready. Connect this demo form to your preferred email or CRM endpoint before launch.", choose: "Select a product", both: "Quinoa & Chia Seeds", contactDirect: "Commercial inquiries", directText: "For a faster assessment, include your destination port, required certification, pack format and first-order volume.", emailValue: "sales@altiplanoharvest.com", hours: "Response target", hoursValue: "Within 1–2 business days",
    footer: "Bolivian quinoa and chia for global food businesses.", rights: "All rights reserved.", disclaimer: "Product availability, certification and final specifications are confirmed per quotation."
  },
  es: {
    home: "Inicio", about: "Nosotros", products: "Productos", quality: "Calidad", packaging: "Empaque", contact: "Contacto",
    eyebrow: "Cultivado en altura. Suministrado al mundo.", heroTitle: "Superalimentos bolivianos, listos para su mercado.", heroText: "Quinua Real y semillas de chía para importadores, distribuidores y fabricantes — seleccionadas con cuidado en el Altiplano boliviano.", quote: "Solicitar cotización", explore: "Ver productos",
    trust1: "Abastecimiento de origen", trust2: "Suministro exportable", trust3: "Formatos flexibles", trust4: "Servicio B2B",
    introEyebrow: "De la altura a la oportunidad", introTitle: "Una ruta confiable a ingredientes bolivianos auténticos.", introText: "Conectamos compradores internacionales con quinua y chía cuidadosamente seleccionadas, mediante especificaciones claras, comunicación ágil y soporte práctico de exportación.", learn: "Conozca nuestro enfoque",
    productsEyebrow: "Nuestro portafolio", productsTitle: "Dos ingredientes poderosos. Múltiples posibilidades.", quinoa: "Quinua Real Boliviana", quinoaText: "Granos grandes y distintivos de las zonas de altura de Bolivia, disponibles en variedades blanca, roja y negra.", chia: "Semillas de Chía", chiaText: "Semillas limpias y uniformes para panadería, bebidas, cereales, snacks y formulaciones saludables.", view: "Ver detalles",
    buyerTitle: "Pensado para la forma de trabajar del comprador B2B.", buyerText: "Desde muestras y fichas técnicas hasta empaque y documentos de envío, facilitamos cada paso para evaluar y avanzar.", buyer1: "Especificaciones claras", buyer2: "Muestras comerciales a pedido", buyer3: "Marca privada y granel", buyer4: "Soporte documental de exportación",
    ctaTitle: "Construyamos su próximo programa de suministro.", ctaText: "Indíquenos producto, volumen, destino y empaque. Nuestro equipo responderá con opciones comerciales adecuadas.",
    aboutEyebrow: "Sobre Altiplano Harvest", aboutTitle: "Raíces en Bolivia. Enfoque global.", aboutLead: "Somos un proveedor B2B especializado que conecta las condiciones extraordinarias del Altiplano boliviano con empresas alimentarias de todo el mundo.", storyTitle: "Un socio de abastecimiento especializado", storyText: "Nuestro trabajo comienza con el ajuste correcto: origen, variedad, especificación y formato para cada cliente. Colaboramos con socios experimentados cerca del origen y coordinamos los detalles que necesita el comprador internacional, desde las muestras hasta el embarque.", valuesTitle: "Cómo trabajamos", value1: "Claridad", value1t: "Respuestas directas, documentos útiles y plazos realistas.", value2: "Consistencia", value2t: "Especificaciones definidas y programas de suministro repetibles.", value3: "Colaboración", value3t: "Apoyo práctico para relaciones comerciales a largo plazo.",
    productPageTitle: "Ingredientes con historia — y especificación.", productPageLead: "Seleccione el origen, variedad y formato para su línea. Las especificaciones finales se confirman con cada cotización.", white: "Quinua Real Blanca", whiteT: "Sabor suave y color claro para retail, bowls, panadería y alimentos preparados.", red: "Quinua Real Roja", redT: "Textura firme y color intenso para mezclas, ensaladas y aplicaciones premium.", black: "Quinua Real Negra", blackT: "Granos oscuros distintivos para mezclas coloridas y gamas especiales.", chiaT: "Semillas enteras de sabor neutro para alimentos funcionales, panadería y bebidas.", details: "Opciones habituales", optQ: "Convencional u orgánica • limpia • grano entero • granel", optC: "Convencional u orgánica • limpia • semilla entera • granel", askSpec: "Solicitar ficha técnica",
    qualityPageTitle: "Calidad que puede evaluar antes de comprar.", qualityPageLead: "Un proceso transparente basado en especificaciones facilita una compra segura y una recepción consistente.", flow1: "01 · Selección de proveedor", flow1t: "Los socios de origen se evalúan por capacidad, consistencia y preparación exportadora.", flow2: "02 · Control de lote", flow2t: "Cada lote se identifica y maneja según la especificación acordada.", flow3: "03 · Análisis", flow3t: "Los parámetros de calidad e inocuidad se confirman según lote y requisito.", flow4: "04 · Documentación", flow4t: "Coordinamos documentos comerciales y de producto para el mercado de destino.", docTitle: "Documentación a pedido", docs: "Ficha técnica • Certificado de análisis • Documentos orgánicos cuando aplique • Lista de empaque • Factura comercial • Documentos de origen y envío",
    packPageTitle: "Empaque pensado para producto, pallet y marca.", packPageLead: "Elija formatos prácticos para uso industrial, distribución o programas listos para retail.", bulk: "Suministro a granel", bulkT: "Formatos comunes: sacos de papel multicapa con liner o sacos de polipropileno tejido. Pesos típicos: 20 kg, 25 kg o según acuerdo.", private: "Marca privada", privateT: "Podemos desarrollar bolsas retail según volumen, arte, normativa y requisitos de producción.", logistics: "Pallet y logística", logisticsT: "El patrón de pallet, carga de contenedor y marcas se confirman antes del envío.", customTitle: "¿Necesita un formato personalizado?", customText: "Comparta peso, material, volumen anual, idioma de etiqueta y destino. Evaluaremos la ruta más práctica.",
    contactPageTitle: "Inicie una conversación clara y útil.", contactPageLead: "Envíe su requerimiento y responderemos con disponibilidad, especificaciones y próximos pasos.", formTitle: "Solicitar cotización", name: "Nombre", company: "Empresa", email: "Correo empresarial", country: "País / mercado", interest: "Producto de interés", volume: "Volumen estimado", message: "Requisitos", send: "Enviar consulta", sent: "Gracias — su consulta está lista. Conecte este formulario de demostración con su correo o CRM antes del lanzamiento.", choose: "Seleccione un producto", both: "Quinua y Chía", contactDirect: "Consultas comerciales", directText: "Para una evaluación ágil, incluya puerto de destino, certificación, formato y volumen inicial.", emailValue: "sales@altiplanoharvest.com", hours: "Tiempo de respuesta", hoursValue: "1–2 días hábiles",
    footer: "Quinua y chía bolivianas para empresas alimentarias globales.", rights: "Todos los derechos reservados.", disclaimer: "Disponibilidad, certificación y especificaciones finales se confirman en cada cotización."
  }
};

const pageMeta: Record<PageKey, { title: string; image: string }> = {
  home: { title: "Altiplano Harvest", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2000&q=85" },
  about: { title: "About", image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=85" },
  products: { title: "Products", image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=2000&q=85" },
  quality: { title: "Quality", image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=2000&q=85" },
  packaging: { title: "Packaging", image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=2000&q=85" },
  contact: { title: "Contact", image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2000&q=85" }
};

function Arrow() { return <span aria-hidden="true">↗</span>; }

export function Site({ page }: { page: PageKey }) {
  const [lang, setLang] = useState<Lang>("en");
  const [menu, setMenu] = useState(false);
  const [sent, setSent] = useState(false);
  const t = copy[lang];
  useEffect(() => { const saved = localStorage.getItem("ah-lang") as Lang | null; if (saved) setLang(saved); }, []);
  function switchLang(next: Lang) { setLang(next); localStorage.setItem("ah-lang", next); document.documentElement.lang = next; }
  function submit(e: FormEvent) { e.preventDefault(); setSent(true); }
  const links: [PageKey, string][] = [["home", t.home], ["about", t.about], ["products", t.products], ["quality", t.quality], ["packaging", t.packaging], ["contact", t.contact]];

  const products = [
    ["white", t.white, t.whiteT, "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85"],
    ["red", t.red, t.redT, "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=1000&q=85"],
    ["black", t.black, t.blackT, "https://images.unsplash.com/photo-1608797178974-15b35a64ede9?auto=format&fit=crop&w=1000&q=85"],
    ["chia", t.chia, t.chiaT, "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85"]
  ];

  return <div className="site">
    <header className="header">
      <Link className="brand" href="/" aria-label="Altiplano Harvest home"><span className="brandMark">AH</span><span>ALTIPLANO<br/><b>HARVEST</b></span></Link>
      <button className="menuButton" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Toggle navigation">{menu ? "×" : "☰"}</button>
      <nav className={menu ? "nav open" : "nav"} aria-label="Main navigation">{links.map(([key, label]) => <Link key={key} className={page === key ? "active" : ""} href={key === "home" ? "/" : `/${key}`} onClick={() => setMenu(false)}>{label}</Link>)}</nav>
      <div className="language" aria-label="Language"><button className={lang === "en" ? "selected" : ""} onClick={() => switchLang("en")}>EN</button><span>/</span><button className={lang === "es" ? "selected" : ""} onClick={() => switchLang("es")}>ES</button></div>
    </header>

    {page === "home" ? <main>
      <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(13,47,40,.88),rgba(13,47,40,.24)),url(${pageMeta.home.image})`}}>
        <div className="heroInner"><p className="eyebrow light">{t.eyebrow}</p><h1>{t.heroTitle}</h1><p className="heroCopy">{t.heroText}</p><div className="actions"><Link className="button primary" href="/contact">{t.quote} <Arrow/></Link><Link className="button ghost" href="/products">{t.explore}</Link></div></div>
        <div className="originBadge"><span>∞</span><small>BOLIVIAN<br/>ORIGIN</small></div>
      </section>
      <section className="trustStrip">{[t.trust1,t.trust2,t.trust3,t.trust4].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</section>
      <section className="split section"><div className="imageFrame tall"><img src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85" alt="Andes mountain landscape in Bolivia"/></div><div className="content"><p className="eyebrow">{t.introEyebrow}</p><h2>{t.introTitle}</h2><p>{t.introText}</p><Link className="textLink" href="/about">{t.learn} <Arrow/></Link></div></section>
      <section className="productsFeature section"><div className="sectionHead"><div><p className="eyebrow">{t.productsEyebrow}</p><h2>{t.productsTitle}</h2></div></div><div className="featureGrid"><ProductFeature image={products[0][3]} title={t.quinoa} text={t.quinoaText} link={t.view}/><ProductFeature image={products[3][3]} title={t.chia} text={t.chiaText} link={t.view}/></div></section>
      <section className="buyer section"><div><p className="eyebrow light">B2B READY</p><h2>{t.buyerTitle}</h2><p>{t.buyerText}</p></div><div className="checkGrid">{[t.buyer1,t.buyer2,t.buyer3,t.buyer4].map(x=><div key={x}><span>✓</span>{x}</div>)}</div></section>
      <Cta t={t}/>
    </main> : <main>
      <PageHero page={page} t={t}/>
      {page === "about" && <><section className="split section"><div className="imageFrame"><img src="https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85" alt="Bolivian Altiplano landscape"/></div><div className="content"><p className="eyebrow">OUR ROLE</p><h2>{t.storyTitle}</h2><p>{t.storyText}</p></div></section><section className="section values"><p className="eyebrow">PRINCIPLES</p><h2>{t.valuesTitle}</h2><div className="threeGrid">{[[t.value1,t.value1t],[t.value2,t.value2t],[t.value3,t.value3t]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section><Cta t={t}/></>}
      {page === "products" && <><section className="section productGrid">{products.map(([key,title,text,image],i)=><article className="productCard" key={key}><img src={image} alt={title}/><div><span className="productNo">0{i+1}</span><h2>{title}</h2><p>{text}</p><h3>{t.details}</h3><p className="spec">{key === "chia" ? t.optC : t.optQ}</p><Link href="/contact" className="textLink">{t.askSpec} <Arrow/></Link></div></article>)}</section><Cta t={t}/></>}
      {page === "quality" && <><section className="section qualityFlow">{[[t.flow1,t.flow1t],[t.flow2,t.flow2t],[t.flow3,t.flow3t],[t.flow4,t.flow4t]].map(([a,b])=><article key={a}><h2>{a}</h2><p>{b}</p></article>)}</section><section className="documentPanel section"><div><p className="eyebrow light">BUYER FILE</p><h2>{t.docTitle}</h2></div><p>{t.docs}</p></section><Cta t={t}/></>}
      {page === "packaging" && <><section className="section packagingGrid">{[[t.bulk,t.bulkT,"20 / 25 KG"],[t.private,t.privateT,"PRIVATE LABEL"],[t.logistics,t.logisticsT,"EXPORT READY"]].map(([a,b,c],i)=><article key={a}><div className={`packVisual pack${i}`}><span>{c}</span></div><h2>{a}</h2><p>{b}</p></article>)}</section><section className="customPack section"><div><h2>{t.customTitle}</h2><p>{t.customText}</p></div><Link className="button primary" href="/contact">{t.quote} <Arrow/></Link></section></>}
      {page === "contact" && <section className="contactGrid section"><div className="contactAside"><p className="eyebrow">{t.contactDirect}</p><h2>{t.emailValue}</h2><p>{t.directText}</p><div className="contactFact"><span>{t.hours}</span><b>{t.hoursValue}</b></div></div><form className="form" onSubmit={submit}><h2>{t.formTitle}</h2><div className="fieldRow"><label>{t.name}<input required name="name"/></label><label>{t.company}<input required name="company"/></label></div><div className="fieldRow"><label>{t.email}<input required name="email" type="email"/></label><label>{t.country}<input required name="country"/></label></div><div className="fieldRow"><label>{t.interest}<select required name="product"><option value="">{t.choose}</option><option>{t.quinoa}</option><option>{t.chia}</option><option>{t.both}</option></select></label><label>{t.volume}<input name="volume" placeholder="e.g. 20 MT"/></label></div><label>{t.message}<textarea name="message" rows={5}/></label><button className="button primary" type="submit">{t.send} <Arrow/></button>{sent && <p className="success" role="status">{t.sent}</p>}</form></section>}
    </main>}

    <footer><div className="footerBrand"><div className="brand"><span className="brandMark">AH</span><span>ALTIPLANO<br/><b>HARVEST</b></span></div><p>{t.footer}</p></div><div className="footerLinks">{links.slice(1).map(([key,label])=><Link key={key} href={`/${key}`}>{label}</Link>)}</div><div className="footerBottom"><span>© {new Date().getFullYear()} Altiplano Harvest. {t.rights}</span><span>{t.disclaimer}</span></div></footer>
  </div>;
}

function ProductFeature({image,title,text,link}:{image:string,title:string,text:string,link:string}) { return <article className="featureCard"><div><img src={image} alt={title}/></div><span className="miniLabel">BULK INGREDIENT</span><h3>{title}</h3><p>{text}</p><Link href="/products" className="textLink">{link} <Arrow/></Link></article>; }
function Cta({t}:{t:Copy}) { return <section className="cta section"><div><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p></div><Link className="button cream" href="/contact">{t.quote} <Arrow/></Link></section>; }
function PageHero({page,t}:{page:PageKey,t:Copy}) { const title = page === "about" ? t.aboutTitle : page === "products" ? t.productPageTitle : page === "quality" ? t.qualityPageTitle : page === "packaging" ? t.packPageTitle : t.contactPageTitle; const lead = page === "about" ? t.aboutLead : page === "products" ? t.productPageLead : page === "quality" ? t.qualityPageLead : page === "packaging" ? t.packPageLead : t.contactPageLead; const eyebrow = page === "about" ? t.aboutEyebrow : t[page]; return <section className="pageHero" style={{backgroundImage:`linear-gradient(90deg,rgba(13,47,40,.92),rgba(13,47,40,.35)),url(${pageMeta[page].image})`}}><div><p className="eyebrow light">{eyebrow}</p><h1>{title}</h1><p>{lead}</p></div></section>; }
